name: 02-workfloe-events

on: 
    push:
    pull_request:
    schedule:
        - cron: '*/5 * * * *' # Runs every day at midnight
    workflow_dispatch: # Allow the manual trigger from the UI of the github 

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the triggering event
              run: echo "I have been triggered by the ${{ github.event_name }} event"